AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HonoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda/index.handler
      Runtime: nodejs22.x
      Timeout: 30
      Environment:
        Variables:
          NODE_ENV: development
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        HttpApiRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

Outputs:
  HonoFunctionApi:
    Description: "Local API Gateway endpoint URL"
    Value: "http://127.0.0.1:3000"